// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_APPNote_screen_init(void)
{
    ui_APPNote = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_APPNote, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_APPNote, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_APPNote, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image2, ui_img_zero_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image2, 5);
    lv_obj_set_y(ui_Image2, 5);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_APPNote);
    lv_obj_set_width(ui_Panel11, 45);
    lv_obj_set_height(ui_Panel11, 16);
    lv_obj_set_x(ui_Panel11, 237);
    lv_obj_set_y(ui_Panel11, 5);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel11, ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel1 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_timeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel1, "15:21");
    lv_obj_set_style_text_color(ui_timeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_APPNote);
    lv_bar_set_value(ui_Bar3, 96, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 29);
    lv_obj_set_height(ui_Bar3, 13);
    lv_obj_set_x(ui_Bar3, 286);
    lv_obj_set_y(ui_Bar3, 5);
    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x666633), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLabel1 = lv_label_create(ui_Bar3);
    lv_obj_set_width(ui_powerLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel1, "96%");
    lv_obj_set_style_text_color(ui_powerLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_APP = lv_label_create(ui_APPNote);
    lv_obj_set_width(ui_APP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_APP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_APP, -10);
    lv_obj_set_y(ui_APP, -72);
    lv_obj_set_align(ui_APP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_APP, "AppName");

    ui_Panel13 = lv_obj_create(ui_APPNote);
    lv_obj_set_width(ui_Panel13, 267);
    lv_obj_set_height(ui_Panel13, 89);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -13);
    lv_obj_set_y(ui_Label4, -31);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "INSTALL");

    ui_Bar5 = lv_bar_create(ui_Panel13);
    lv_bar_set_value(ui_Bar5, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 230);
    lv_obj_set_height(ui_Bar5, 10);
    lv_obj_set_x(ui_Bar5, 2);
    lv_obj_set_y(ui_Bar5, -3);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -7);
    lv_obj_set_y(ui_Label9, 15);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "0%");

    ui_Button1 = lv_btn_create(ui_Panel13);
    lv_obj_set_width(ui_Button1, 78);
    lv_obj_set_height(ui_Button1, 27);
    lv_obj_set_x(ui_Button1, 73);
    lv_obj_set_y(ui_Button1, 21);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "cancel");

    ui_Container1 = lv_obj_create(ui_APPNote);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 320);
    lv_obj_set_height(ui_Container1, -146);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_appinstall = lv_btn_create(ui_APPNote);
    lv_obj_set_width(ui_appinstall, 50);
    lv_obj_set_height(ui_appinstall, 12);
    lv_obj_set_x(ui_appinstall, 5);
    lv_obj_set_y(ui_appinstall, 23);
    lv_obj_add_flag(ui_appinstall, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_appinstall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_appinstall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_appinstall);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "install");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appremove = lv_btn_create(ui_APPNote);
    lv_obj_set_width(ui_appremove, 50);
    lv_obj_set_height(ui_appremove, 12);
    lv_obj_set_x(ui_appremove, 61);
    lv_obj_set_y(ui_appremove, 23);
    lv_obj_add_flag(ui_appremove, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_appremove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_appremove, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_appremove);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "remove");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appupdate = lv_btn_create(ui_APPNote);
    lv_obj_set_width(ui_appupdate, 50);
    lv_obj_set_height(ui_appupdate, 12);
    lv_obj_set_x(ui_appupdate, 118);
    lv_obj_set_y(ui_appupdate, 23);
    lv_obj_add_flag(ui_appupdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_appupdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_appupdate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_appupdate);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "update");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_APPNote);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 186);
    lv_obj_set_y(ui_Label3, 23);
    lv_label_set_text(ui_Label3, "V0.01--->v0.02");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image6, ui_img_zero_logo_w_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 58
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image8, ui_img_zuo_logo_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image10, ui_img_you_logo_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image12, ui_img_detail_info_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 197
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image14, ui_img_down_logo_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image16, ui_img_up_logo_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_APPNote);
    lv_img_set_src(ui_Image18, ui_img_camera_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_appinstall, ui_event_appinstall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_appremove, ui_event_appremove, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_appupdate, ui_event_appupdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_APPNote, ui_event_APPNote, LV_EVENT_ALL, NULL);

}
