// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_AppStore_screen_init(void)
{
    ui_AppStore = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AppStore, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppStore, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppStore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_AppStore);
    lv_img_set_src(ui_Image4, ui_img_zero_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image4, 5);
    lv_obj_set_y(ui_Image4, 5);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_AppStore);
    lv_obj_set_width(ui_Panel12, 45);
    lv_obj_set_height(ui_Panel12, 16);
    lv_obj_set_x(ui_Panel12, 237);
    lv_obj_set_y(ui_Panel12, 5);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel12, ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel3 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_timeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel3, "15:21");
    lv_obj_set_style_text_color(ui_timeLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_AppStore);
    lv_bar_set_value(ui_Bar4, 96, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 29);
    lv_obj_set_height(ui_Bar4, 13);
    lv_obj_set_x(ui_Bar4, 286);
    lv_obj_set_y(ui_Bar4, 5);
    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x666633), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLabel3 = lv_label_create(ui_Bar4);
    lv_obj_set_width(ui_powerLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel3, "96%");
    lv_obj_set_style_text_color(ui_powerLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_AppStore);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -10);
    lv_obj_set_y(ui_Label1, -72);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "AppStore");

    ui_Label5 = lv_label_create(ui_AppStore);
    lv_obj_set_width(ui_Label5, 320);
    lv_obj_set_height(ui_Label5, 16);
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 75);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Version: v0.01");

    ui_Container4 = lv_obj_create(ui_AppStore);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 320);
    lv_obj_set_height(ui_Container4, 130);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 3);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AppStore, ui_event_AppStore, LV_EVENT_ALL, NULL);

}
