// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_AppStore2_screen_init(void)
{
    ui_AppStore2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AppStore2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppStore2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppStore2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoLabel = lv_label_create(ui_AppStore2);
    lv_obj_set_width(ui_logoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logoLabel, -137);
    lv_obj_set_y(ui_logoLabel, -74);
    lv_obj_set_align(ui_logoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logoLabel, "ZERO");
    lv_obj_set_style_text_color(ui_logoLabel, lv_color_hex(0xE5B700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_logoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_AppStore2);
    lv_obj_set_width(ui_Panel24, 40);
    lv_obj_set_height(ui_Panel24, 13);
    lv_obj_set_x(ui_Panel24, 206);
    lv_obj_set_y(ui_Panel24, 3);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "19:45");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_AppStore2);
    lv_obj_set_width(ui_Panel25, 30);
    lv_obj_set_height(ui_Panel25, 13);
    lv_obj_set_x(ui_Panel25, 248);
    lv_obj_set_y(ui_Panel25, 3);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel26, 5);
    lv_obj_set_height(ui_Panel26, 3);
    lv_obj_set_x(ui_Panel26, -11);
    lv_obj_set_y(ui_Panel26, 2);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x00CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel27, 5);
    lv_obj_set_height(ui_Panel27, 6);
    lv_obj_set_x(ui_Panel27, -4);
    lv_obj_set_y(ui_Panel27, 1);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x00CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel28 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel28, 5);
    lv_obj_set_height(ui_Panel28, 7);
    lv_obj_set_x(ui_Panel28, 3);
    lv_obj_set_y(ui_Panel28, 0);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0x00CCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Panel25);
    lv_obj_set_width(ui_Panel29, 5);
    lv_obj_set_height(ui_Panel29, 9);
    lv_obj_set_x(ui_Panel29, 10);
    lv_obj_set_y(ui_Panel29, -1);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_AppStore2);
    lv_obj_set_width(ui_Panel30, 38);
    lv_obj_set_height(ui_Panel30, 13);
    lv_obj_set_x(ui_Panel30, 280);
    lv_obj_set_y(ui_Panel30, 3);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "100%");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_AppStore2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 320);
    lv_obj_set_height(ui_Container6, 150);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 10);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zuoPanel2 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_zuoPanel2, 81);
    lv_obj_set_height(ui_zuoPanel2, 81);
    lv_obj_set_x(ui_zuoPanel2, -99);
    lv_obj_set_y(ui_zuoPanel2, -16);
    lv_obj_set_align(ui_zuoPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_zuoPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_zuoPanel2, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_zuoPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zuoPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_zuoPanel2, ui_img_store_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_zuoPanel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_zuoPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youbut2 = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_youbut2, 17);
    lv_obj_set_height(ui_youbut2, 23);
    lv_obj_set_x(ui_youbut2, 150);
    lv_obj_set_y(ui_youbut2, -14);
    lv_obj_set_align(ui_youbut2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_youbut2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_youbut2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_youbut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_youbut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_youbut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_youbut2, ui_img_you_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_youbut2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_youbut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoLabel2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_zuoLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zuoLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zuoLabel2, -99);
    lv_obj_set_y(ui_zuoLabel2, 47);
    lv_obj_set_align(ui_zuoLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zuoLabel2, "STORE");
    lv_obj_set_style_text_color(ui_zuoLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zuoLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchLabel2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_switchLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switchLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switchLabel2, 0);
    lv_obj_set_y(ui_switchLabel2, 40);
    lv_obj_set_align(ui_switchLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_switchLabel2, "CLI");
    lv_obj_set_style_text_color(ui_switchLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switchLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youLabel2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_youLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_youLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_youLabel2, 99);
    lv_obj_set_y(ui_youLabel2, 47);
    lv_obj_set_align(ui_youLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_youLabel2, "CLAW");
    lv_obj_set_style_text_color(ui_youLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_youLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outPanelzuo2 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_outPanelzuo2, 61);
    lv_obj_set_height(ui_outPanelzuo2, 61);
    lv_obj_set_x(ui_outPanelzuo2, -177);
    lv_obj_set_y(ui_outPanelzuo2, -6);
    lv_obj_set_align(ui_outPanelzuo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_outPanelzuo2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_outPanelzuo2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_outPanelzuo2, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outPanelzuo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outPanelzuo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_outPanelzuo2, ui_img_python_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_outPanelzuo2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_outPanelzuo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outPanelyou2 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_outPanelyou2, 61);
    lv_obj_set_height(ui_outPanelyou2, 61);
    lv_obj_set_x(ui_outPanelyou2, 177);
    lv_obj_set_y(ui_outPanelyou2, -6);
    lv_obj_set_align(ui_outPanelyou2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_outPanelyou2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_outPanelyou2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_outPanelyou2, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outPanelyou2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outPanelyou2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_outPanelyou2, ui_img_setting_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_outPanelyou2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_outPanelyou2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuoLabelout2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_zuoLabelout2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zuoLabelout2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zuoLabelout2, -177);
    lv_obj_set_y(ui_zuoLabelout2, 47);
    lv_obj_set_align(ui_zuoLabelout2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zuoLabelout2, "one");
    lv_obj_add_flag(ui_zuoLabelout2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_zuoLabelout2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zuoLabelout2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youLabelout2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_youLabelout2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_youLabelout2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_youLabelout2, 177);
    lv_obj_set_y(ui_youLabelout2, 47);
    lv_obj_set_align(ui_youLabelout2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_youLabelout2, "three");
    lv_obj_add_flag(ui_youLabelout2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_youLabelout2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_youLabelout2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchPanel2 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_switchPanel2, 101);
    lv_obj_set_height(ui_switchPanel2, 101);
    lv_obj_set_x(ui_switchPanel2, 0);
    lv_obj_set_y(ui_switchPanel2, -26);
    lv_obj_set_align(ui_switchPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_switchPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switchPanel2, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switchPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_switchPanel2, ui_img_cli_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_switchPanel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_switchPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youPanel2 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_youPanel2, 81);
    lv_obj_set_height(ui_youPanel2, 81);
    lv_obj_set_x(ui_youPanel2, 99);
    lv_obj_set_y(ui_youPanel2, -16);
    lv_obj_set_align(ui_youPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_youPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_youPanel2, 17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_youPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_youPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_youPanel2, ui_img_claw_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_youPanel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_youPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zuobut2 = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_zuobut2, 17);
    lv_obj_set_height(ui_zuobut2, 23);
    lv_obj_set_x(ui_zuobut2, -151);
    lv_obj_set_y(ui_zuobut2, -14);
    lv_obj_set_align(ui_zuobut2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zuobut2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zuobut2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_zuobut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_zuobut2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zuobut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_zuobut2, ui_img_zuo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_zuobut2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_zuobut2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 320);
    lv_obj_set_height(ui_Container7, 10);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, 60);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel33 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel33, 10);
    lv_obj_set_height(ui_Panel33, 10);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0xCCCC33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel33, lv_color_hex(0x4A4C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel33, lv_color_hex(0xCCCC33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_zuoPanel2, ui_event_zuoPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youbut2, ui_event_youbut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outPanelzuo2, ui_event_outPanelzuo2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outPanelyou2, ui_event_outPanelyou2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchPanel2, ui_event_switchPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youPanel2, ui_event_youPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zuobut2, ui_event_zuobut2, LV_EVENT_ALL, NULL);

}
