// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_clawapp_screen_init(void)
{
    ui_clawapp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clawapp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clawapp, lv_color_hex(0x5F52E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clawapp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_clawapp);
    lv_img_set_src(ui_Image3, ui_img_zero_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image3, 5);
    lv_obj_set_y(ui_Image3, 5);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_clawapp);
    lv_obj_set_width(ui_Panel2, 45);
    lv_obj_set_height(ui_Panel2, 16);
    lv_obj_set_x(ui_Panel2, 237);
    lv_obj_set_y(ui_Panel2, 5);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel2, ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_timeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel2, "15:21");
    lv_obj_set_style_text_color(ui_timeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_clawapp);
    lv_bar_set_value(ui_Bar2, 96, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 29);
    lv_obj_set_height(ui_Bar2, 13);
    lv_obj_set_x(ui_Bar2, 286);
    lv_obj_set_y(ui_Bar2, 5);
    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x666633), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLabel2 = lv_label_create(ui_Bar2);
    lv_obj_set_width(ui_powerLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel2, "96%");
    lv_obj_set_style_text_color(ui_powerLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_clawapp);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -10);
    lv_obj_set_y(ui_Label8, -72);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "AppCLAW");

    ui_Container2 = lv_obj_create(ui_clawapp);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 94);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -14);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_claw = lv_textarea_create(ui_clawapp);
    lv_obj_set_width(ui_claw, 320);
    lv_obj_set_height(ui_claw, 50);
    lv_obj_set_x(ui_claw, 0);
    lv_obj_set_y(ui_claw, 59);
    lv_obj_set_align(ui_claw, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_claw, "help:");
    lv_obj_set_style_radius(ui_claw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_claw, lv_color_hex(0x7378E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_claw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clawapp, ui_event_clawapp, LV_EVENT_ALL, NULL);

}
