// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_pythonapp_screen_init(void)
{
    ui_pythonapp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pythonapp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pythonapp, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pythonapp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_pythonapp);
    lv_img_set_src(ui_Image5, ui_img_zero_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image5, 5);
    lv_obj_set_y(ui_Image5, 5);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_pythonapp);
    lv_obj_set_width(ui_Panel14, 45);
    lv_obj_set_height(ui_Panel14, 16);
    lv_obj_set_x(ui_Panel14, 237);
    lv_obj_set_y(ui_Panel14, 5);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel14, ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel4 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_timeLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel4, "15:21");
    lv_obj_set_style_text_color(ui_timeLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar6 = lv_bar_create(ui_pythonapp);
    lv_bar_set_value(ui_Bar6, 96, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 29);
    lv_obj_set_height(ui_Bar6, 13);
    lv_obj_set_x(ui_Bar6, 286);
    lv_obj_set_y(ui_Bar6, 5);
    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x666633), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_powerLabel4 = lv_label_create(ui_Bar6);
    lv_obj_set_width(ui_powerLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powerLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel4, "96%");
    lv_obj_set_style_text_color(ui_powerLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_pythonapp);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -10);
    lv_obj_set_y(ui_Label11, -72);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AppPython");

    ui_Container3 = lv_obj_create(ui_pythonapp);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 320);
    lv_obj_set_height(ui_Container3, 144);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 13);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pythonapp, ui_event_pythonapp, LV_EVENT_ALL, NULL);

}
