// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"
#include "../ui_helpers.h"
#include "ui_comp.h"

uint32_t LV_EVENT_GET_COMP_CHILD;
uint32_t LV_EVENT_KEYBOARD;

typedef struct {
    uint32_t child_idx;
    lv_obj_t * child;
} ui_comp_get_child_t;

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx)
{
    ui_comp_get_child_t info;
    info.child = NULL;
    info.child_idx = child_idx;
    lv_event_send(comp, LV_EVENT_GET_COMP_CHILD, &info);
    return info.child;
}

void get_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = lv_event_get_user_data(e);
    ui_comp_get_child_t * info = lv_event_get_param(e);
    info->child = c[info->child_idx];
}

void del_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = lv_event_get_user_data(e);
    lv_free(c);
}



// void ui_AppStore_add_TabPage(lv_obj_t * ui_TabPage)
// {
//     ui_Image2 = lv_img_create(ui_TabPage);
//     lv_obj_set_width(ui_Image2, 20);
//     lv_obj_set_height(ui_Image2, 20);
//     lv_obj_set_x(ui_Image2, -121);
//     lv_obj_set_y(ui_Image2, -48);
//     lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
//     lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label4 = lv_label_create(ui_TabPage);
//     lv_obj_set_width(ui_Label4, 243);
//     lv_obj_set_height(ui_Label4, 75);
//     lv_obj_set_x(ui_Label4, -4);
//     lv_obj_set_y(ui_Label4, 9);
//     lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label4, "a ssh tools,support ssh.");

//     ui_Button2 = lv_btn_create(ui_TabPage);
//     lv_obj_set_width(ui_Button2, 60);
//     lv_obj_set_height(ui_Button2, 18);
//     lv_obj_set_x(ui_Button2, -35);
//     lv_obj_set_y(ui_Button2, -46);
//     lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label9 = lv_label_create(ui_Button2);
//     lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label9, -1);
//     lv_obj_set_y(ui_Label9, 0);
//     lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label9, "install");

//     ui_Button4 = lv_btn_create(ui_TabPage);
//     lv_obj_set_width(ui_Button4, 60);
//     lv_obj_set_height(ui_Button4, 18);
//     lv_obj_set_x(ui_Button4, 28);
//     lv_obj_set_y(ui_Button4, -46);
//     lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label10 = lv_label_create(ui_Button4);
//     lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label10, "remove");

//     ui_Button5 = lv_btn_create(ui_TabPage);
//     lv_obj_set_width(ui_Button5, 60);
//     lv_obj_set_height(ui_Button5, 18);
//     lv_obj_set_x(ui_Button5, 92);
//     lv_obj_set_y(ui_Button5, -46);
//     lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label11 = lv_label_create(ui_Button5);
//     lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label11, -1);
//     lv_obj_set_y(ui_Label11, 0);
//     lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label11, "update");
// }