// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "../ui.h"

void ui_AppStore1_screen_init1(void)
{

    lv_obj_del(ui_Roller1);
    ui_Roller1 = lv_roller_create(ui_AppStore1);
    lv_roller_set_options(ui_Roller1, "Option 1\nCAMERA      v1.1\nOption 3\nOption 4\nOption 5", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller1, 1, LV_ANIM_OFF);
    lv_roller_set_visible_row_count(ui_Roller1, 5);
    lv_obj_set_width(ui_Roller1, 196);
    lv_obj_set_height(ui_Roller1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Roller1, 50);
    lv_obj_set_y(ui_Roller1, -14);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_line_space(ui_Roller1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Roller1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Roller1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
}
